name: CI Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '21'

      - name: Update and install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb libgtk-3-0

      - name: Build with Gradle
        run: xvfb-run ./gradlew build

      - name: Aggregate Jacoco Report
        run: |
          ./gradlew AggregateJacocoReport
          mv build/reports/jacoco/aggregate/html ./coverage
          mv build/reports/jacoco/aggregate/jacocoTestReport.xml ./coverage/report.xml
          echo $(cat coverage/index.html | grep -o -E "Total[^%]+?%" | sed -E "s/<.*>//" | sed -E "s/Total/TestCoverage:/")

      - name: Upload Coverage Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage
